##############################################################################
# Copyright (c) 2013-2016, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
#
# This file is part of Spack.
# Created by Todd Gamblin, tgamblin@llnl.gov, All rights reserved.
# LLNL-CODE-647188
#
# For details, see https://github.com/llnl/spack
# Please also see the LICENSE file for our notice and the LGPL.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License (as
# published by the Free Software Foundation) version 2.1, February 1999.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms and
# conditions of the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
##############################################################################
from spack import *


class Qcachegrind(Package):
    """Profile visualization of data generated by Cachegrind."""

    homepage = "https://kcachegrind.github.io/html/Home.html"
    url      = "https://download.kde.org/stable/applications/16.12.0/src/kcachegrind-16.12.0.tar.xz"

    version('16.12.0', 'ce16b8e893f151cdf454e04535205efc')

    variant('graphviz', default=True,  description='Compile with graphviz')

    depends_on("qt")
    depends_on("graphviz", when='+graphviz', type='run')

    def install(self, spec, prefix):
        with working_dir('qcachegrind', create=false):
            qmake = which('qmake')
            qmake('-r')
            make()
            make("install")
